// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exDefault.Models;

namespace exDefault.Migrations
{
    [DbContext(typeof(EntitiesDbContext))]
    [Migration("20190626191007_addComment")]
    partial class addComment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("exDefault.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EntityId");

                    b.Property<bool>("Important");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("exDefault.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOff");

                    b.Property<DateTime>("DateOn");

                    b.Property<int>("EntityType");

                    b.Property<bool>("IsOrNot");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("exDefault.Models.Comment", b =>
                {
                    b.HasOne("exDefault.Models.Entity")
                        .WithMany("Comments")
                        .HasForeignKey("EntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
